# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabe Yuan
email: Yugang2002@Gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life was like a box of chocolates.
  You never know what you're gonna get.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fishjar.com" # the base hostname & protocol for your site
twitter_username: FishJar
github_username:  FishJar
timezone: Asia/Shanghai

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

# Outputting
permalink: /blog/:title.html

